name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
     steps:
       - name: Check out the repo
        uses: actions/checkout@v3

       - name: Login to Docker Hub
         uses: docker/login-action@2
         with: 
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build and push Docker image
         uses: docker/build-push-action@4
         with: 
           context: DockerFolder/
           push: true
           tags: momsomrach1168/gitdockerci:latest
